name: glyc-ml
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas=2.2
  - numpy=1.26
  - scikit-learn=1.5
  - xgboost=2.1
  - matplotlib=3.9
  - shap=0.45
  - pyyaml=6.0
  - joblib=1.4
  - scipy=1.13
  - pip
  - pip:
      - category-encoders==2.6.3
